name: Build Game and Publish to Github Pages

on:
  push:
    branch: main

jobs:
  build_and_deploy:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: Setup Godot
        uses: lihop/setup-godot@v0.1.1

      - name: Run demo
        shell: bash
        run: godot --export --no-window

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
